version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      - ":8080"
    labels:
      - "traefik.docker.network=traefik-proxy" 
      - "traefik.enable=true"
      - "traefik.http.middlewares.searx-https-redirect.redirectscheme.scheme=https" 
      - "traefik.http.routers.searx-secure.entrypoints=https"
      - "traefik.http.routers.searx-secure.rule=Host(`search.thievent.org`)"
      - "traefik.http.routers.searx-secure.service=searx"
      - "traefik.http.routers.searx-secure.tls=true"
      - "traefik.http.routers.searx-secure.tls.certresolver=http"
      - "traefik.http.routers.searx.entrypoints=http"
      - "traefik.http.routers.searx.middlewares=searx-https-redirect"
      - "traefik.http.routers.searx.rule=Host(`search.thievent.org`)"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:
